import { generateText, type ModelMessage } from "ai";
import { loggerServiceMain, type MessageContentPart } from "@shared";
import { tMain } from "../../i18n";
import { getDefaultModelByType } from "../settings/settingsData";
import { resolveModelInvocation } from "../providers/modelInvocation";
import {
  getLocaleInstructionLabel,
  resolveTargetResponseLocale,
} from "../language/responseLocale";

const logger = loggerServiceMain.withContext("titleService");
const AUTO_GENERATED_IMAGE_PROMPT = "Please describe the image content.";

function isAutoGeneratedImagePrompt(value: string): boolean {
  return (value ?? "").trim() === AUTO_GENERATED_IMAGE_PROMPT;
}

export function fallbackTitleFromFirstMessage(parts: MessageContentPart[], maxChars = 12) {
  // 提取文本和图片数量
  const textParts = parts
    .filter((part) => part.type === 'text')
    .map((part) => part.text)
    .join('');
  
  const imageCount = parts.filter((part) => part.type === 'file' && part.mediaType.startsWith('image/')).length;
  
  const normalized = (textParts ?? "")
    .trim()
    .replace(/\s+/g, " ");

  // 如果有图片但没有文本，或者文本是兜底提示
  if (imageCount > 0 && (!normalized || isAutoGeneratedImagePrompt(normalized))) {
    return imageCount === 1
      ? tMain("title.defaultImageSingle")
      : tMain("title.defaultImageMultiple", { count: imageCount });
  }

  if (!normalized) return tMain("title.defaultNewSession");
  if (normalized.length <= maxChars) return normalized;
  return normalized.slice(0, maxChars);
}

function cleanupModelTitle(raw: string) {
  let s = (raw ?? "").trim();
  if (!s) return "";

  // 取第一行，避免模型输出多行解释
  s = s.split(/\r?\n/)[0]?.trim() ?? "";

  // 去掉常见包裹符号（引号/书名号等）
  s = s.replace(/^["'“”‘’《》「」【】]+/, "").replace(/["'“”‘’《》「」【】]+$/, "").trim();

  // 去掉 markdown code fence（避免模型包了一层代码块）
  s = s.replace(/^```+/, "").replace(/```+$/, "").trim();

  // 再次压缩空白
  s = s.replace(/\s+/g, " ").trim();
  return s;
}

function isValidTitle(title: string) {
  const t = (title ?? "").trim();
  if (!t) return false;
  return t.length > 0;
}

export async function generateSessionTitleByFastModel(params: {
  parts: MessageContentPart[];
  timeoutMs?: number;
}) {
  const timeoutMs = params.timeoutMs ?? 15000;

  const fast = getDefaultModelByType("fast");
  if (!fast?.providerId || !fast?.modelId) {
    return { ok: false as const, error: tMain("title.fastModelNotConfigured") };
  }

  let provider: ReturnType<typeof resolveModelInvocation>["provider"];
  let client: ReturnType<typeof resolveModelInvocation>["client"];
  try {
    const resolved = resolveModelInvocation({ providerId: fast.providerId, modelId: fast.modelId });
    provider = resolved.provider;
    client = resolved.client;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { ok: false as const, error: message };
  }

  // 提取文本部分
  const textParts = params.parts
    .filter((part) => part.type === 'text')
    .map((part) => part.text)
    .join('');
  
  // 统计图片数量
  const imageCount = params.parts.filter((part) => part.type === 'file' && part.mediaType.startsWith('image/')).length;
  
  // 构造给 AI 的 prompt：文本 + 图片数量提示
  let actualPrompt: string;
  if (imageCount > 0) {
    const imageHint = imageCount === 1 ? "[contains 1 image]" : `[contains ${imageCount} images]`;
    // 如果文本为空或是兜底提示，只保留图片提示
    if (!textParts.trim() || isAutoGeneratedImagePrompt(textParts.trim())) {
      actualPrompt = imageHint;
    } else {
      actualPrompt = `${textParts.trim()} ${imageHint}`;
    }
  } else {
    actualPrompt = textParts.trim();
  }

  const targetLocale = resolveTargetResponseLocale({
    currentUserText: textParts.trim(),
  });
  const targetLanguage = getLocaleInstructionLabel(targetLocale);

  const systemPrompt = [
    "You are a conversation title generator.",
    "Task: produce a concise topic title for the user's message(s). This is a title, not a reply.",
    "Output rules: output the title only. No explanation, no quotes, no markdown, no extra lines.",
    `Language rule: the title MUST be written in ${targetLanguage}.`,
    "Style: prefer noun phrases. Do not use first person. Do not phrase it as a question or an answer.",
    "Disallowed content: do not mention model or product self-identifiers (for example ChatGPT).",
    "Punctuation: avoid sentence-ending punctuation unless it is essential to the title.",
    "Length rules (language-adaptive):",
    "- Pure English: 2 to 7 words.",
    "- Chinese or mixed Chinese/English: 4 to 16 Chinese characters (or a similarly concise equivalent).",
    "The title must be semantically complete and understandable on its own.",
    "Avoid vague labels such as problem, question, help, or greeting unless the content genuinely requires them.",
    "If multiple loose topics appear, choose the main topic or synthesize one concise umbrella title instead of listing topics.",
    "Examples:",
    'User: Introduce yourself briefly -> Self Introduction',
    'User: Help me write a weekly report template -> Weekly Report Template',
    'User: css transform translateZ(0) causes click failure -> CSS Click Failure Cause',
    'User: difference between electron renderer and main -> Electron Process Differences',
    'User: [contains 1 image] -> Image Question',
    'User: how to build this interface [contains 2 images] -> UI Implementation Plan',
  ].join('\n');

  const messages: ModelMessage[] = [
    { role: "system", content: systemPrompt },
    {
      role: "user",
      content: `Target language: ${targetLanguage}

User message:
${actualPrompt}`,
    },
  ];

  const abort = new AbortController();
  const timer = setTimeout(() => abort.abort(), timeoutMs);

  logger.info("generate title: calling generateText", {
    providerId: fast.providerId,
    modelId: fast.modelId,
    actualPrompt,
    timeoutMs,
  });

  try {
    const { text } = await generateText({
      model: client(fast.modelId),
      messages,
      temperature: 0.1,
      // maxOutputTokens: 512,
      abortSignal: abort.signal,
      // 快速任务不需要 thinking，告知 provider 禁用（支持的会生效，不支持的忽略）
      providerOptions: {
        [fast.providerId]: { think: { type: 'disable' as const } },
      },
    });

    const cleaned = cleanupModelTitle(text);
    if (!isValidTitle(cleaned)) {
      logger.warn("generate title: model returned invalid/empty title", { raw: text, cleaned });
      return { ok: false as const, error: tMain("title.invalidResult") };
    }

    logger.info("generated title by light task model", {
      providerId: fast.providerId,
      modelId: fast.modelId,
      actualPrompt,
      title: cleaned,
    });

    return { ok: true as const, title: cleaned };
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    const err = e as Record<string, unknown>;
    const providerDetails: Record<string, unknown> = { message };
    if (err.statusCode != null) providerDetails.statusCode = err.statusCode;
    if (err.responseBody != null) providerDetails.responseBody = err.responseBody;
    if (err.cause != null) providerDetails.cause = err.cause instanceof Error ? err.cause.message : String(err.cause);
    logger.warn("generate title failed", providerDetails);
    return { ok: false as const, error: message };
  } finally {
    clearTimeout(timer);
  }
}
