/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAccordion: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UAlert: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UAvatarGroup: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue')['default']
    UBadge: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCalendar: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue')['default']
    UCard: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UChip: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Chip.vue')['default']
    UCollapsible: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UColorPicker: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue')['default']
    UContextMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue')['default']
    UDropdownMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UEditor: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Editor.vue')['default']
    UEditorDragHandle: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue')['default']
    UEditorSuggestionMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue')['default']
    UEditorToolbar: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue')['default']
    UEmpty: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Empty.vue')['default']
    UFieldGroup: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UFileUpload: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFormField: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputDate: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue')['default']
    UInputNumber: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UInputTime: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue')['default']
    UKbd: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UModal: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPopover: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UProgress: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    URadioGroup: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    UScrollArea: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/ScrollArea.vue')['default']
    USelect: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USlider: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    USwitch: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTimeline: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue')['default']
    UTooltip: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    UTree: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap+pm@3._7mmqmxxwy37x5b25d5mwo2b2wy/node_modules/@nuxt/ui/dist/runtime/components/Tree.vue')['default']
  }
}
